### PR TITLE
Off-diagonal values may no longer be nonzero if the diagonal is zero for a covariance matrix

### PR DESCRIPTION
**Pull request by billdenney**
Fix nlmixr2/rxode2#481

### CODE REVIEW

**Comment by mattfidler** [comment]
I'm uncomfortable with the breaking change as it is written (while I agree with the need).  `lotri` could be used in contexts other than covariances (though unlikely).

**Comment by billdenney** [comment]
Should I add an argument like `isCov=TRUE` that enables this error or when set to FALSE, it would not trigger the error?

**Comment by mattfidler** [comment]
Yes, that would be the theory.  I used `cov` instead and added a few test conditions.

Also this needs to be tested in nested/occasion

**Comment by mattfidler** [comment]
I also saw some edge cases that are not handled correctly by adding this flag...

**Comment by mattfidler** [comment]
It could be why the environment grows in certain circumstances...

**Comment by mattfidler** [comment]
I have mostly finished.  I will upload when I get computer internet access again.

The only oustanding piece for me is why is this an error instead of a warning that corrects the matrix?

The reason I ask is since this is now only applied for covariance matrices, lotri should also check for positive definite matrices (which the code will).  Since getting a positive definite matrix is not always intuitive, the code can optionally find the nearest positive definite matrix by providing some sort of correction funtion.

This would make the zero correction strategy proposed here inconsistent with the non positive definite correction.

I may be missing why this should be an error instead of a correction and warning.

**Comment by billdenney** [comment]
I would think that typos would be the most common reason it would have a nonzero covariance with a zero variance.  In that case, I would rather see an error than have an auto correction that may not be the correction I wanted.

**Comment by mattfidler** [comment]
@billdenney 

Let me know if this looks good to you now.

**Comment by billdenney** [comment]
Looks good to me.  Thanks!

**Pull request merged**
